### ISSUE TITLE
Retaining scroll position from the previous page

### ISSUE THREAD

**Issue by Edouardbozon** [rogerpadilla/prouter#18]
Hi, :hand: 

I'm building a small PWA using a prouter. By reading the PWA checklist I saw that is a good practice to retain scroll position from the previous page when user presses back.

Imagine a list of a product, the user scroll to the bottom of the list, pick a product and go to the detail page. Then he goes back to the list. In this case, it's good to restore the scroll position.

It can be a nice to have feature in prouter. What do you think ?

**Comment by rogerpadilla** [comment]
Hi @Edouardbozon ,

I am happy of seeing prouter useful for your PWA! And yes, I agree this could be useful. The thing is each application is different, that is why prouter tries to be as un-opinionated (also in pro of being minimalist and fast) as possible about the way each application should behave; for example, scroll-restoration might not apply for pages with infinite-scroll navigation. On the other hand, I am thinking this could be supported/implemented via a new configuration parameter in a future version of prouter.

In the meantime (to avoid making you wait for that possible new feature being added to prouter), I think this could be easily achieved via prouter's '.on' navigation callback (the callback receives an object with two properties: oldPath, newPat -  I will add more documentation about this soon) to store and restore scroll position based on URLs: basically, you could preserve the scroll-position per page using an object where each property of this would be an URL and the scroll-position would be the value of that property.

Note: there is a [native](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration) browser feature for scroll position restoration, which can even be [customized](https://www.ccdatalab.org/blog/automatic-scroll-restoration-single-page-applications).

Please let me know any further question or comment.

**Comment by Edouardbozon** [comment]
@rogerpadilla Thanks for the quick response, I didn't know about the native scroll restoration api, thanks for pointing this. I think I will use the navigation event as you said to avoid compatibility issues.

**Comment by Edouardbozon** [comment]
Hi! I just finished a small implementation based on URLs as you described. But I have a little problem, when I push the history back button from my browser the `.on('navigation', ... )` is never triggered.

Is it a normal behavior ?

**Comment by rogerpadilla** [comment]
Hi, yeah, not triggering _navigation_ event in that case was a bug! I just published version 9.1.1 which corrects that (in this commit https://github.com/rogerpadilla/prouter/commit/3c81a6e27e807b92382fb1bc9d74ed507b9abb78).

Please check and feel free to reopen this issue if you found any additional issue.
