### ISSUE TITLE
.navigate doesn't scroll to top

### ISSUE THREAD

**Issue by olalonde** [rogerpadilla/prouter#3]
When calling `.navigate` from a page where the user has scrolled down, the window will still be positioned where it was instead of going back to the top like normally happens when clicking links.

**Comment by rogerpadilla** [comment]
This library is intended to be used when you want to react to URL (path) changes, and to trigger some callbacks (handlers) accordingly.

The documentation was also updated with useful and clearer examples. Please check and let me know. This time I'll answer much faster, I promise :)
