### ISSUE TITLE
Instructions unclear and so on...

### ISSUE THREAD

**Issue by jpeltoniemi** [rogerpadilla/prouter#4]
This may seem like a dumb issue but I can't seem to load prouter. I've tried regular script tags and requirejs, and failed miserably. According to readme.md either method should work.

The file I've been trying to load is _dist/index.js_ as it's the only js file that isn't a configuration file. I must be doing something wrong but I have no idea what it is. Care to point me in the right direction (and amend readme.md so other dummies like me don't get stuck right away)? :)

**Comment by rogerpadilla** [comment]
There was an issue, it is fixed now. The documentation was also updated with useful and clearer examples. Please check and let me know. This time I'll answer much faster, I promise :)
